---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: kafka-proxy
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: kafka-proxy
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 30